
POST  http://localhost:3000/user HTTP/1.1
content-type: application/json

{
  "email": "amiraizin@gmail.com",
  "firstName": "amir",
  "lastName": "aizinn"
}

###

GET http://localhost:3000/user/e91940cbb423cae5 HTTP/1.1

###

PATCH http://localhost:3000/user/e91940cbb423cae5 HTTP/1.1
content-type: application/json

{
  "firstName": "amir",
  "profilePicture": "https://i.stack.imgur.com/Bb6z1.jpg?s=64&g=1"
}

###


DELETE http://localhost:3000/user/e91940cbb423cae5 HTTP/1.1

###
